apiVersion: apps/v1
kind: Deployment
metadata:
  name: alpha
  labels:
    app: alpha
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: alpha
  template:
    metadata:
      labels:
        app: alpha
    spec:
      containers:
        - name: alpha
          image: {{.Values.image.repository}}
          imagePullPolicy: Always
          command: ["/bin/sh"]
          args: ["-c", "/bin/ist -s 0.0.0.0:9000 -t beta:9001"]
          resources:
            requests:
              memory: "0.5Gi"
            limits:
              memory: "1Gi"
          ports:
            - containerPort: 9000
              name: grpc
              protocol: TCP
