apiVersion: apps/v1
kind: Deployment
metadata:
  name: charlie
  labels:
    app: charlie
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: charlie
  template:
    metadata:
      labels:
        app: charlie
    spec:
      containers:
        - name: charlie
          image: {{.Values.image.repository}}
          imagePullPolicy: Always
          command: ["/bin/sh"]
          args: ["-c", "/bin/ist -r {{ .Values.remoteUrl }}"]
          resources:
            requests:
              memory: "0.5Gi"
            limits:
              memory: "1Gi"
