{{ range $n , $value := .Values.deployments }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ $value.name }}
  namespace: {{ $value.namespace }}
spec:
  hosts:
    - {{ $value.name }}
  gateways:
    - {{ $value.gateway }}
  tcp:
    - route:
        - destination:
            host: {{ $value.name }}
            port:
              number: {{ $value.port }}
---

{{ end }}
